### ISSUE TITLE
Create initial list of general interview questions

### ISSUE THREAD

**Issue by asteed21** [wildlifehexagon/bears-team-27#2]

**Comment by ermarie** [comment]
Can you tell me a little about yourself?
Why should we hire you?
What are your greatest professional strengths?
What do you consider to be your weaknesses?
What is your greatest professional achievement?
Tell me about a challenge or conflict you've faced at work, and how you dealt with it.
Where do you see yourself in five years?
What's your dream job?
Why are you leaving your current job?
What are you looking for in a new position?
What type of work environment do you prefer?
What's a time you exercised leadership?
What's a time you disagreed with a decision that was made at work?
How would your boss and co-workers describe you?
Why was there a gap in your employment?
Can you explain why you changed career paths?
How do you deal with pressure or stressful situations?
What would your first 30, 60, or 90 days look like in this role?
What do you like to do outside of work?
If you were an animal, which one would you want to be?

From: https://www.themuse.com/advice/how-to-answer-the-31-most-common-interview-questions

**Comment by ermarie** [comment]
Talk about a time when you had to work closely with someone whose personality was very different from yours.

Give me an example of a time you faced a conflict while working on a team. How did you handle that?

Describe a time when you struggled to build a relationship with someone important. How did you eventually overcome that?

We all make mistakes we wish we could take back. Tell me about a time you wish you’d handled a situation differently with a colleague.

Tell me about a time you needed to get information from someone who wasn’t very responsive. What did you do?

Describe a time when it was especially important to make a good impression on a client. How did you go about doing so?

Give me an example of a time when you did not meet a client’s expectation. What happened, and how did you attempt to rectify the situation?

Tell me about a time when you made sure a customer was pleased with your service.

Describe a time when you had to interact with a difficult client. What was the situation, and how did you handle it?

When you’re working with a large number of customers, it’s tricky to deliver excellent service to them all. How do you go about prioritizing your customers’ needs?

Tell me about a time you were under a lot of pressure. What was going on, and how did you get through it?

Describe a time when your team or company was undergoing some change. How did that impact you, and how did you adapt?

Tell me about the first job you’ve ever had. What did you do to learn the ropes?

Give me an example of a time when you had to think on your feet in order to delicately extricate yourself from a difficult or awkward situation.

Tell me about a time you failed. How did you deal with this situation?

Tell me about a time you had to be very strategic in order to meet all your top priorities.

Describe a long-term project that you managed. How did you keep everything moving along in a timely manner?

Sometimes it’s just not possible to get everything on your to-do list done. Tell me about a time your responsibilities got a little overwhelming. What did you do?

Tell me about a time you set a goal for yourself. How did you go about ensuring that you would meet your objective?

Give me an example of a time you managed numerous responsibilities. How did you handle that?

Give me an example of a time when you were able to successfully persuade someone to see things your way at work.

Describe a time when you were the resident technical expert. What did you do to make sure everyone was able to understand you?

Tell me about a time when you had to rely on written communication to get your ideas across to your team.

Give me an example of a time when you had to explain something fairly complex to a frustrated client. How did you handle this delicate situation?

Tell me about a successful presentation you gave and why you think it was a hit.

Tell me about your proudest professional accomplishment.

Describe a time when you saw some problem and took the initiative to correct it rather than waiting for someone else to do it.

Tell me about a time when you worked under close supervision or extremely loose supervision. How did you handle that?

Give me an example of a time you were able to be creative with your work. What was exciting or difficult about it?

Tell me about a time you were dissatisfied in your work. What could have been done to make it better?

From: https://www.themuse.com/advice/30-behavioral-interview-questions-you-should-be-ready-to-answer-1

**Comment by ermarie** [comment]
What can you offer us that someone else can not?
What are three things your former manager would like you to improve on?
Tell me about a time you made a mistake.
Discuss your resume.
Discuss your educational background.
Describe yourself.
Tell me how you handled a difficult situation.
How would you deal with an angry or irate customer?
Give a time when you went above and beyond the requirements for a project.
What was your biggest failure?
What motivates you?
Who’s your mentor?
What gets you up in the morning?
Are you a leader or a follower?
What was the last book you’ve read for fun?
What is your favorite website?
What makes you uncomfortable?
What are some of your leadership experiences?

From: https://www.glassdoor.com/blog/common-interview-questions/

**Comment by ermarie** [comment]
So I'm steering away from company specific questions like "How did you find this job?" or "What do you know about our company?" because while I think they are important questions to be prepared for, I feel like as a general interview prep, they don't really fit in great because a person isn't necessarily prepping for a specific interview.

**Comment by ermarie** [comment]
How would you describe yourself in one word?
How does this position compare to others you are applying for?
Have you ever considered being an entrepreneur?
Have you ever stolen a pen from work?
What kind of boss and coworkers have you had the most and least success with, and why?
If you could work for any company, where would you work?
How do you define success?
What career regrets do you have?
What would you do if you won $5 million tomorrow?
Have you ever been asked to compromise your integrity by your supervisor or colleague? Tell us about it.
Can you give us a reason someone may not like working with you?
Tell me about a time you disagreed with a company policy.
How did you make time for this interview? Where does your boss think you are right now?

From: http://www.businessinsider.com/job-interview-questions-that-will-trick-you-2016-9/#whats-a-difficult-situation-that-you-turned-around-describe-it-to-us-21

**Comment by asteed21** [comment]
Agreed with the approach of avoiding the really subjective company-centric questions. This looks like a great list for us to get started with for the general section. If you guys agree it's enough to kick things off, I reckon we can go ahead and close this issue. Thanks @ermarie for gathering.

**Comment by erichartline** [comment]
Yeah this is awesome, thanks @ermarie!
